device = device(type='cuda')
[INFO 08-08 08:52:09] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter lr. If that is not the expected value type, you can explicity specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 08-08 08:52:09] ax.service.utils.instantiation: Inferred value type of ParameterType.INT for parameter batch_size. If that is not the expected value type, you can explicity specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 08-08 08:52:09] ax.service.utils.instantiation: Created search space: SearchSpace(parameters=[RangeParameter(name='lr', parameter_type=FLOAT, range=[1e-06, 0.03], log_scale=True), RangeParameter(name='batch_size', parameter_type=INT, range=[16, 128]), RangeParameter(name='weight_decay', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[]).
[INFO 08-08 08:52:09] ax.modelbridge.dispatch_utils: Using Bayesian optimization since there are more ordered parameters than there are categories for the unordered categorical parameters.
[INFO 08-08 08:52:09] ax.modelbridge.dispatch_utils: Using Bayesian Optimization generation strategy: GenerationStrategy(name='Sobol+GPEI', steps=[Sobol for 6 trials, GPEI for subsequent trials]). Iterations after 6 will take longer to generate due to  model-fitting.
[INFO 08-08 08:52:09] ax.service.managed_loop: Started full optimization with 20 steps.
[INFO 08-08 08:52:09] ax.service.managed_loop: Running optimization trial 1...
/home/sayko/.local/lib/python3.8/site-packages/scipy/optimize/minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated
  warnings.warn('Covariance of the parameters could not be estimated',
0	2900.1240	2768.9072	282484.4062	156.14
1	1473.1088	1447.6030	289001.9375	158.36
97307.546875
[INFO 08-08 08:57:25] ax.service.managed_loop: Running optimization trial 2...
/home/sayko/.local/lib/python3.8/site-packages/scipy/optimize/minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated
  warnings.warn('Covariance of the parameters could not be estimated',
0	1944.7622	2867.6685	11669.2158	146.26
1	2190.1648	2056.6733	10835.5293	146.79
5027.4560546875
[INFO 08-08 09:02:18] ax.service.managed_loop: Running optimization trial 3...
/home/sayko/.local/lib/python3.8/site-packages/scipy/optimize/minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated
  warnings.warn('Covariance of the parameters could not be estimated',
0	8444.2471	11489.0830	259531.7344	198.16
1	8902.3262	17448.6387	93410.1484	197.56
39920.375
[INFO 08-08 09:08:54] ax.service.managed_loop: Running optimization trial 4...
/home/sayko/.local/lib/python3.8/site-packages/scipy/optimize/minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated
  warnings.warn('Covariance of the parameters could not be estimated',
0	10091.1436	11463.4463	68227.4844	182.57
1	10241.6777	16993.5430	13471.2080	182.80
13568.810546875
[INFO 08-08 09:15:00] ax.service.managed_loop: Running optimization trial 5...
/home/sayko/.local/lib/python3.8/site-packages/scipy/optimize/minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated
  warnings.warn('Covariance of the parameters could not be estimated',
0	1143.9965	1263.6809	92717.7891	149.34
1	2737.1025	2145.0635	14839.5908	147.42
6573.91943359375
[INFO 08-08 09:19:57] ax.service.managed_loop: Running optimization trial 6...
/home/sayko/.local/lib/python3.8/site-packages/scipy/optimize/minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated
  warnings.warn('Covariance of the parameters could not be estimated',
0	24926.7207	19998.5176	17331.9570	190.92
1	51107.3359	18984.6875	16846.8809	191.24
28979.63671875
[INFO 08-08 09:26:20] ax.service.managed_loop: Running optimization trial 7...
/home/sayko/.local/lib/python3.8/site-packages/gpytorch/lazy/lazy_tensor.py:1810: UserWarning: torch.triangular_solve is deprecated in favor of torch.linalg.solve_triangularand will be removed in a future PyTorch release.
torch.linalg.solve_triangular has its arguments reversed and does not return a copy of one of the inputs.
X = torch.triangular_solve(B, A).solution
should be replaced with
X = torch.linalg.solve_triangular(A, B). (Triggered internally at  ../aten/src/ATen/native/BatchLinearAlgebra.cpp:2189.)
  Linv = torch.triangular_solve(Eye, L, upper=False).solution
/home/sayko/.local/lib/python3.8/site-packages/scipy/optimize/minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated
  warnings.warn('Covariance of the parameters could not be estimated',
0	2771.2866	3319.0410	9208.8594	145.13
1	3918.7769	2518.2800	5016.0835	144.76
3817.713623046875
[INFO 08-08 09:31:10] ax.service.managed_loop: Running optimization trial 8...
/home/sayko/.local/lib/python3.8/site-packages/scipy/optimize/minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated
  warnings.warn('Covariance of the parameters could not be estimated',
0	3225.9929	3760.0938	5959.2158	147.46
1	3451.6448	4673.5562	4508.7012	147.39
4211.30078125
[INFO 08-08 09:36:05] ax.service.managed_loop: Running optimization trial 9...
[INFO 08-08 09:36:06] ax.modelbridge.base: Untransformed parameter 0.030000000000000013 greater than upper bound 0.03, clamping
/home/sayko/.local/lib/python3.8/site-packages/scipy/optimize/minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated
  warnings.warn('Covariance of the parameters could not be estimated',
0	2556.5793	3681.0505	6743.9595	146.37
1	2480.2805	2636.3179	5714.8442	146.64
3610.481201171875
[INFO 08-08 09:40:59] ax.service.managed_loop: Running optimization trial 10...
[INFO 08-08 09:40:59] ax.modelbridge.base: Untransformed parameter 0.030000000000000013 greater than upper bound 0.03, clamping
/home/sayko/.local/lib/python3.8/site-packages/scipy/optimize/minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated
  warnings.warn('Covariance of the parameters could not be estimated',
0	1702.7991	1616.8147	3968.4707	146.17
1	879.3914	336.9254	510.8652	146.07
575.727294921875
[INFO 08-08 09:45:52] ax.service.managed_loop: Running optimization trial 11...
/home/sayko/.local/lib/python3.8/site-packages/scipy/optimize/minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated
  warnings.warn('Covariance of the parameters could not be estimated',
0	723.4128	712.2099	163143.0156	149.88
1	2267.2451	2390.0391	19102.3301	145.98
7919.87109375
[INFO 08-08 09:50:48] ax.service.managed_loop: Running optimization trial 12...
/home/sayko/.local/lib/python3.8/site-packages/scipy/optimize/minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated
  warnings.warn('Covariance of the parameters could not be estimated',
0	2551.1294	1763.7573	30256.9180	147.98
1	596.3039	770.8051	761.3961	147.98
709.5016479492188
[INFO 08-08 09:55:45] ax.service.managed_loop: Running optimization trial 13...
[INFO 08-08 09:55:45] ax.modelbridge.base: Untransformed parameter 0.030000000000000013 greater than upper bound 0.03, clamping
[ERROR 08-08 09:55:47] ax.service.managed_loop: Encountered exception during optimization: 
Traceback (most recent call last):
  File "/home/sayko/.local/lib/python3.8/site-packages/ax/service/managed_loop.py", line 226, in full_run
    self.run_trial()
  File "/home/sayko/.local/lib/python3.8/site-packages/ax/utils/common/executils.py", line 147, in actual_wrapper
    return func(*args, **kwargs)
  File "/home/sayko/.local/lib/python3.8/site-packages/ax/service/managed_loop.py", line 204, in run_trial
    raw_data={
  File "/home/sayko/.local/lib/python3.8/site-packages/ax/service/managed_loop.py", line 205, in <dictcomp>
    arm.name: self._call_evaluation_function(arm.parameters, weight)
  File "/home/sayko/.local/lib/python3.8/site-packages/ax/service/managed_loop.py", line 144, in _call_evaluation_function
    evaluation = self.evaluation_function(parameterization)
  File "googlenet_serial.py", line 211, in train_evaluate
    trained_net, avg_error = net_train(net = untrained_net, parameters=parameterization, device=device, dtype=dtype)
  File "googlenet_serial.py", line 191, in net_train
    Pe = ryan.recalc_pe_prediction(device, Bg_pred, Bth_pred, eta_sp, resolution, batch_size).to(device)
  File "/media/sayko/storage1/test_pe_fitting/predict_2/res_96_fit/optim/recalc_pe.py", line 90, in recalc_pe_prediction
    popt, pcov = curve_fit(pe_fit_function, x, y)
  File "/home/sayko/.local/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 743, in curve_fit
    xdata = np.asarray_chkfinite(xdata, float)
  File "/home/sayko/.local/lib/python3.8/site-packages/numpy/lib/function_base.py", line 488, in asarray_chkfinite
    raise ValueError(
ValueError: array must not contain infs or NaNs
{'lr': 0.00024692411298567337, 'batch_size': 120, 'weight_decay': 0.0}
{'error': 658.94212242289}
{'error': {'error': 6269280.567652856}}
